const appointmentsData = [
  {
    id: "A001",
    patientName: "John Doe",
    age: 45,
    phone: "+1-555-1234",
    date: "2025-05-20",
    time: "10:30 AM",
    status: "Confirmed",
    doctor: "Dr. Smith",
    department: "Cardiology",
    notes: "Follow-up after surgery",
  },
  {
    id: "A002",
    patientName: "Jane Smith",
    age: 32,
    phone: "+1-555-5678",
    date: "2025-05-21",
    time: "11:00 AM",
    status: "Pending",
    doctor: "Dr. Johnson",
    department: "Dermatology",
    notes: "Skin rash consultation",
  },
  {
    id: "A003",
    patientName: "Alice Johnson",
    age: 28,
    phone: "+1-555-8765",
    date: "2025-05-22",
    time: "09:00 AM",
    status: "Cancelled",
    doctor: "Dr. Lee",
    department: "Neurology",
    notes: "Initial consultation",
  },
  {
    id: "A004",
    patientName: "Bob Brown",
    age: 52,
    phone: "+1-555-4321",
    date: "2025-05-23",
    time: "01:30 PM",
    status: "Confirmed",
    doctor: "Dr. Patel",
    department: "Orthopedics",
    notes: "Post-accident checkup",
  },
  {
    id: "A005",
    patientName: "Carol White",
    age: 40,
    phone: "+1-555-6789",
    date: "2025-05-24",
    time: "02:45 PM",
    status: "Pending",
    doctor: "Dr. Singh",
    department: "Pediatrics",
    notes: "Annual vaccination",
  },
  {
    id: "A006",
    patientName: "David Green",
    age: 37,
    phone: "+1-555-1357",
    date: "2025-05-25",
    time: "03:15 PM",
    status: "Confirmed",
    doctor: "Dr. Kim",
    department: "Ophthalmology",
    notes: "Eye examination",
  },
  {
    id: "A007",
    patientName: "Eve Black",
    age: 29,
    phone: "+1-555-2468",
    date: "2025-05-26",
    time: "11:45 AM",
    status: "Confirmed",
    doctor: "Dr. Garcia",
    department: "ENT",
    notes: "Hearing test",
  },
  {
    id: "A008",
    patientName: "Frank Blue",
    age: 54,
    phone: "+1-555-9753",
    date: "2025-05-27",
    time: "12:00 PM",
    status: "Pending",
    doctor: "Dr. Martinez",
    department: "General Medicine",
    notes: "General check-up",
  },
  {
    id: "A009",
    patientName: "Grace Yellow",
    age: 33,
    phone: "+1-555-8642",
    date: "2025-05-28",
    time: "10:15 AM",
    status: "Cancelled",
    doctor: "Dr. Wilson",
    department: "Psychiatry",
    notes: "Therapy session",
  },
  {
    id: "A010",
    patientName: "Henry Orange",
    age: 46,
    phone: "+1-555-3698",
    date: "2025-05-29",
    time: "09:30 AM",
    status: "Confirmed",
    doctor: "Dr. Hernandez",
    department: "Cardiology",
    notes: "ECG test",
  },
  {
    id: "A011",
    patientName: "Ivy Violet",
    age: 39,
    phone: "+1-555-1122",
    date: "2025-06-01",
    time: "10:00 AM",
    status: "Confirmed",
    doctor: "Dr. Moore",
    department: "Endocrinology",
    notes: "Diabetes follow-up",
  },
  {
    id: "A012",
    patientName: "Jack White",
    age: 44,
    phone: "+1-555-3344",
    date: "2025-06-02",
    time: "02:00 PM",
    status: "Pending",
    doctor: "Dr. Clark",
    department: "Gastroenterology",
    notes: "Stomach pain evaluation",
  },
  {
    id: "A013",
    patientName: "Kara Black",
    age: 31,
    phone: "+1-555-5566",
    date: "2025-06-03",
    time: "09:30 AM",
    status: "Confirmed",
    doctor: "Dr. Lewis",
    department: "Rheumatology",
    notes: "Arthritis check",
  },
  {
    id: "A014",
    patientName: "Liam Green",
    age: 48,
    phone: "+1-555-7788",
    date: "2025-06-04",
    time: "01:00 PM",
    status: "Cancelled",
    doctor: "Dr. Young",
    department: "Pulmonology",
    notes: "Asthma treatment",
  },
  {
    id: "A015",
    patientName: "Maya Blue",
    age: 27,
    phone: "+1-555-9900",
    date: "2025-06-05",
    time: "03:45 PM",
    status: "Confirmed",
    doctor: "Dr. Hall",
    department: "Nephrology",
    notes: "Kidney function test",
  },
  {
    id: "A016",
    patientName: "Noah Brown",
    age: 50,
    phone: "+1-555-2233",
    date: "2025-06-06",
    time: "11:15 AM",
    status: "Pending",
    doctor: "Dr. Allen",
    department: "Oncology",
    notes: "Cancer screening",
  },
  {
    id: "A017",
    patientName: "Olivia Red",
    age: 36,
    phone: "+1-555-4455",
    date: "2025-06-07",
    time: "10:30 AM",
    status: "Confirmed",
    doctor: "Dr. King",
    department: "Immunology",
    notes: "Allergy test",
  },
  {
    id: "A018",
    patientName: "Paul Gray",
    age: 42,
    phone: "+1-555-6677",
    date: "2025-06-08",
    time: "02:30 PM",
    status: "Pending",
    doctor: "Dr. Wright",
    department: "Hematology",
    notes: "Blood disorder consultation",
  },
  {
    id: "A019",
    patientName: "Quinn Silver",
    age: 29,
    phone: "+1-555-8899",
    date: "2025-06-09",
    time: "09:00 AM",
    status: "Cancelled",
    doctor: "Dr. Scott",
    department: "Urology",
    notes: "Kidney stone evaluation",
  },
  {
    id: "A020",
    patientName: "Rachel Gold",
    age: 34,
    phone: "+1-555-1010",
    date: "2025-06-10",
    time: "01:45 PM",
    status: "Confirmed",
    doctor: "Dr. Adams",
    department: "Gynecology",
    notes: "Routine checkup",
  },
  {
    id: "A021",
    patientName: "Sam Blue",
    age: 41,
    phone: "+1-555-1212",
    date: "2025-06-11",
    time: "03:00 PM",
    status: "Confirmed",
    doctor: "Dr. Baker",
    department: "Psychology",
    notes: "Counseling session",
  },
  {
    id: "A022",
    patientName: "Tina Orange",
    age: 30,
    phone: "+1-555-1414",
    date: "2025-06-12",
    time: "11:00 AM",
    status: "Pending",
    doctor: "Dr. Carter",
    department: "Otolaryngology",
    notes: "Sinus infection",
  },
  {
    id: "A023",
    patientName: "Uma Violet",
    age: 26,
    phone: "+1-555-1616",
    date: "2025-06-13",
    time: "09:30 AM",
    status: "Confirmed",
    doctor: "Dr. Diaz",
    department: "Dentistry",
    notes: "Dental cleaning",
  },
  {
    id: "A024",
    patientName: "Victor Red",
    age: 38,
    phone: "+1-555-1818",
    date: "2025-06-14",
    time: "02:15 PM",
    status: "Pending",
    doctor: "Dr. Evans",
    department: "Endocrinology",
    notes: "Thyroid check",
  },
  {
    id: "A025",
    patientName: "Wendy Green",
    age: 44,
    phone: "+1-555-2020",
    date: "2025-06-15",
    time: "10:00 AM",
    status: "Cancelled",
    doctor: "Dr. Foster",
    department: "Neurology",
    notes: "Migraine consultation",
  },
  {
    id: "A026",
    patientName: "Xander Black",
    age: 35,
    phone: "+1-555-2222",
    date: "2025-06-16",
    time: "01:30 PM",
    status: "Confirmed",
    doctor: "Dr. Griffin",
    department: "Orthopedics",
    notes: "Fracture check",
  },
  {
    id: "A027",
    patientName: "Yara White",
    age: 28,
    phone: "+1-555-2424",
    date: "2025-06-17",
    time: "03:45 PM",
    status: "Pending",
    doctor: "Dr. Harris",
    department: "Pediatrics",
    notes: "Growth check",
  },
  {
    id: "A028",
    patientName: "Zack Blue",
    age: 47,
    phone: "+1-555-2626",
    date: "2025-06-18",
    time: "11:15 AM",
    status: "Confirmed",
    doctor: "Dr. Johnson",
    department: "Cardiology",
    notes: "Stress test",
  },
  {
    id: "A029",
    patientName: "Amy Rose",
    age: 25,
    phone: "+1-555-2828",
    date: "2025-06-19",
    time: "09:00 AM",
    status: "Confirmed",
    doctor: "Dr. Kim",
    department: "Ophthalmology",
    notes: "Vision test",
  },
  {
    id: "A030",
    patientName: "Brian Black",
    age: 40,
    phone: "+1-555-3030",
    date: "2025-06-20",
    time: "02:00 PM",
    status: "Pending",
    doctor: "Dr. Lee",
    department: "Neurology",
    notes: "Seizure evaluation",
  },
];

export default appointmentsData;
